version: "3"

services:
  sut:
    build: .
    command: up
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/micrate_test
    volumes:
      - ./db:/db:ro

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: micrate_test
